//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAT.PATService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PATService.PatLOBPortType")]
    public interface PatLOBPortType {
        
        // CODEGEN: Generating message contract since the wrapper name (LOBUpload) of message UploadLOBRequest does not match the default value (UploadLOB)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOB_PatWebServices_v1/UploadLOB", ReplyAction="http://tempuri.org/LOB_PatWebServices_v1/UploadLOBResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PAT.PATService.UploadLOBResponse UploadLOB(PAT.PATService.UploadLOBRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (LOBUpload) of message GetLOBWarningsAndErrorsRequest does not match the default value (GetLOBWarningsAndErrors)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOB_PatWebServices_v1/GetLOBWarningsAndErrors", ReplyAction="http://tempuri.org/LOB_PatWebServices_v1/GetLOBWarningsAndErrorsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PAT.PATService.UploadLOBResponse GetLOBWarningsAndErrors(PAT.PATService.UploadLOBRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/LOB_PatWebServices")]
    public partial class LOBDetailRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bookingNumberField;
        
        private string cargoDescriptionField;
        
        private string commVoydocField;
        
        private string commentOneField;
        
        private string commentTwoField;
        
        private string consigneeDODAACField;
        
        private string consignorDODAACField;
        
        private string containerNumberField;
        
        private float cubeField;
        
        private bool cubeFieldSpecified;
        
        private string errorFlagField;
        
        private bool has315vdField;
        
        private bool has315vdFieldSpecified;
        
        private bool hasSiField;
        
        private bool hasSiFieldSpecified;
        
        private string headIDField;
        
        private float heightField;
        
        private bool heightFieldSpecified;
        
        private bool isBookedField;
        
        private bool isBookedFieldSpecified;
        
        private bool isManifestedField;
        
        private bool isManifestedFieldSpecified;
        
        private float lengthField;
        
        private bool lengthFieldSpecified;
        
        private float mtonField;
        
        private bool mtonFieldSpecified;
        
        private string pcfnField;
        
        private string podField;
        
        private string recIDField;
        
        private bool revisedField;
        
        private bool revisedFieldSpecified;
        
        private string tcnField;
        
        private string vanTypeField;
        
        private string vesselStatusField;
        
        private float weightField;
        
        private bool weightFieldSpecified;
        
        private float widthField;
        
        private bool widthFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string bookingNumber {
            get {
                return this.bookingNumberField;
            }
            set {
                this.bookingNumberField = value;
                this.RaisePropertyChanged("bookingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string cargoDescription {
            get {
                return this.cargoDescriptionField;
            }
            set {
                this.cargoDescriptionField = value;
                this.RaisePropertyChanged("cargoDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string commVoydoc {
            get {
                return this.commVoydocField;
            }
            set {
                this.commVoydocField = value;
                this.RaisePropertyChanged("commVoydoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string commentOne {
            get {
                return this.commentOneField;
            }
            set {
                this.commentOneField = value;
                this.RaisePropertyChanged("commentOne");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string commentTwo {
            get {
                return this.commentTwoField;
            }
            set {
                this.commentTwoField = value;
                this.RaisePropertyChanged("commentTwo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string consigneeDODAAC {
            get {
                return this.consigneeDODAACField;
            }
            set {
                this.consigneeDODAACField = value;
                this.RaisePropertyChanged("consigneeDODAAC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string consignorDODAAC {
            get {
                return this.consignorDODAACField;
            }
            set {
                this.consignorDODAACField = value;
                this.RaisePropertyChanged("consignorDODAAC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string containerNumber {
            get {
                return this.containerNumberField;
            }
            set {
                this.containerNumberField = value;
                this.RaisePropertyChanged("containerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float cube {
            get {
                return this.cubeField;
            }
            set {
                this.cubeField = value;
                this.RaisePropertyChanged("cube");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cubeSpecified {
            get {
                return this.cubeFieldSpecified;
            }
            set {
                this.cubeFieldSpecified = value;
                this.RaisePropertyChanged("cubeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string errorFlag {
            get {
                return this.errorFlagField;
            }
            set {
                this.errorFlagField = value;
                this.RaisePropertyChanged("errorFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool has315vd {
            get {
                return this.has315vdField;
            }
            set {
                this.has315vdField = value;
                this.RaisePropertyChanged("has315vd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool has315vdSpecified {
            get {
                return this.has315vdFieldSpecified;
            }
            set {
                this.has315vdFieldSpecified = value;
                this.RaisePropertyChanged("has315vdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool hasSi {
            get {
                return this.hasSiField;
            }
            set {
                this.hasSiField = value;
                this.RaisePropertyChanged("hasSi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasSiSpecified {
            get {
                return this.hasSiFieldSpecified;
            }
            set {
                this.hasSiFieldSpecified = value;
                this.RaisePropertyChanged("hasSiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string headID {
            get {
                return this.headIDField;
            }
            set {
                this.headIDField = value;
                this.RaisePropertyChanged("headID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public float height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("heightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool isBooked {
            get {
                return this.isBookedField;
            }
            set {
                this.isBookedField = value;
                this.RaisePropertyChanged("isBooked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isBookedSpecified {
            get {
                return this.isBookedFieldSpecified;
            }
            set {
                this.isBookedFieldSpecified = value;
                this.RaisePropertyChanged("isBookedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool isManifested {
            get {
                return this.isManifestedField;
            }
            set {
                this.isManifestedField = value;
                this.RaisePropertyChanged("isManifested");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isManifestedSpecified {
            get {
                return this.isManifestedFieldSpecified;
            }
            set {
                this.isManifestedFieldSpecified = value;
                this.RaisePropertyChanged("isManifestedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public float length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
                this.RaisePropertyChanged("lengthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public float mton {
            get {
                return this.mtonField;
            }
            set {
                this.mtonField = value;
                this.RaisePropertyChanged("mton");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mtonSpecified {
            get {
                return this.mtonFieldSpecified;
            }
            set {
                this.mtonFieldSpecified = value;
                this.RaisePropertyChanged("mtonSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string pcfn {
            get {
                return this.pcfnField;
            }
            set {
                this.pcfnField = value;
                this.RaisePropertyChanged("pcfn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string pod {
            get {
                return this.podField;
            }
            set {
                this.podField = value;
                this.RaisePropertyChanged("pod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string recID {
            get {
                return this.recIDField;
            }
            set {
                this.recIDField = value;
                this.RaisePropertyChanged("recID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool revised {
            get {
                return this.revisedField;
            }
            set {
                this.revisedField = value;
                this.RaisePropertyChanged("revised");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revisedSpecified {
            get {
                return this.revisedFieldSpecified;
            }
            set {
                this.revisedFieldSpecified = value;
                this.RaisePropertyChanged("revisedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string tcn {
            get {
                return this.tcnField;
            }
            set {
                this.tcnField = value;
                this.RaisePropertyChanged("tcn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string vanType {
            get {
                return this.vanTypeField;
            }
            set {
                this.vanTypeField = value;
                this.RaisePropertyChanged("vanType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string vesselStatus {
            get {
                return this.vesselStatusField;
            }
            set {
                this.vesselStatusField = value;
                this.RaisePropertyChanged("vesselStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public float weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
                this.RaisePropertyChanged("weightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public float width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("widthSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/LOB_PatWebServices")]
    public partial class LOBValidResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgField;
        
        private bool validField;
        
        private bool validFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validSpecified {
            get {
                return this.validFieldSpecified;
            }
            set {
                this.validFieldSpecified = value;
                this.RaisePropertyChanged("validSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/LOB_PatWebServices")]
    public partial class LOBUpload : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ip_addressField;
        
        private LOBDetailRecord[] lobDetailRecordsField;
        
        private LOBMasterRecord lobMasterField;
        
        private string system_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ip_address {
            get {
                return this.ip_addressField;
            }
            set {
                this.ip_addressField = value;
                this.RaisePropertyChanged("ip_address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public LOBDetailRecord[] lobDetailRecords {
            get {
                return this.lobDetailRecordsField;
            }
            set {
                this.lobDetailRecordsField = value;
                this.RaisePropertyChanged("lobDetailRecords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public LOBMasterRecord lobMaster {
            get {
                return this.lobMasterField;
            }
            set {
                this.lobMasterField = value;
                this.RaisePropertyChanged("lobMaster");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string system_id {
            get {
                return this.system_idField;
            }
            set {
                this.system_idField = value;
                this.RaisePropertyChanged("system_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/LOB_PatWebServices")]
    public partial class LOBMasterRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool metricField;
        
        private bool metricFieldSpecified;
        
        private string poeField;
        
        private System.DateTime sailDateField;
        
        private bool sailDateFieldSpecified;
        
        private string scacField;
        
        private string vesselNameField;
        
        private string voydocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool metric {
            get {
                return this.metricField;
            }
            set {
                this.metricField = value;
                this.RaisePropertyChanged("metric");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metricSpecified {
            get {
                return this.metricFieldSpecified;
            }
            set {
                this.metricFieldSpecified = value;
                this.RaisePropertyChanged("metricSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string poe {
            get {
                return this.poeField;
            }
            set {
                this.poeField = value;
                this.RaisePropertyChanged("poe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime sailDate {
            get {
                return this.sailDateField;
            }
            set {
                this.sailDateField = value;
                this.RaisePropertyChanged("sailDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sailDateSpecified {
            get {
                return this.sailDateFieldSpecified;
            }
            set {
                this.sailDateFieldSpecified = value;
                this.RaisePropertyChanged("sailDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string scac {
            get {
                return this.scacField;
            }
            set {
                this.scacField = value;
                this.RaisePropertyChanged("scac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string vesselName {
            get {
                return this.vesselNameField;
            }
            set {
                this.vesselNameField = value;
                this.RaisePropertyChanged("vesselName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string voydoc {
            get {
                return this.voydocField;
            }
            set {
                this.voydocField = value;
                this.RaisePropertyChanged("voydoc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LOBUpload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadLOBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip_address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/LOB_PatWebServices")]
        public LOBDetailRecord[] lobDetailRecords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PAT.PATService.LOBMasterRecord lobMaster;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string system_id;
        
        public UploadLOBRequest() {
        }
        
        public UploadLOBRequest(string ip_address, LOBDetailRecord[] lobDetailRecords, PAT.PATService.LOBMasterRecord lobMaster, string system_id) {
            this.ip_address = ip_address;
            this.lobDetailRecords = lobDetailRecords;
            this.lobMaster = lobMaster;
            this.system_id = system_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LOBResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadLOBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PAT.PATService.LOBUpload origUpload;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string response;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/LOB_PatWebServices")]
        public LOBValidResponse[] validationResponses;
        
        public UploadLOBResponse() {
        }
        
        public UploadLOBResponse(PAT.PATService.LOBUpload origUpload, string response, LOBValidResponse[] validationResponses) {
            this.origUpload = origUpload;
            this.response = response;
            this.validationResponses = validationResponses;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatLOBPortTypeChannel : PAT.PATService.PatLOBPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatLOBPortTypeClient : System.ServiceModel.ClientBase<PAT.PATService.PatLOBPortType>, PAT.PATService.PatLOBPortType {
        
        public PatLOBPortTypeClient() {
        }
        
        public PatLOBPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatLOBPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatLOBPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatLOBPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PAT.PATService.UploadLOBResponse PAT.PATService.PatLOBPortType.UploadLOB(PAT.PATService.UploadLOBRequest request) {
            return base.Channel.UploadLOB(request);
        }
        
        public PAT.PATService.LOBUpload UploadLOB(string ip_address, LOBDetailRecord[] lobDetailRecords, PAT.PATService.LOBMasterRecord lobMaster, string system_id, out string response, out LOBValidResponse[] validationResponses) {
            PAT.PATService.UploadLOBRequest inValue = new PAT.PATService.UploadLOBRequest();
            inValue.ip_address = ip_address;
            inValue.lobDetailRecords = lobDetailRecords;
            inValue.lobMaster = lobMaster;
            inValue.system_id = system_id;
            PAT.PATService.UploadLOBResponse retVal = ((PAT.PATService.PatLOBPortType)(this)).UploadLOB(inValue);
            response = retVal.response;
            validationResponses = retVal.validationResponses;
            return retVal.origUpload;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PAT.PATService.UploadLOBResponse PAT.PATService.PatLOBPortType.GetLOBWarningsAndErrors(PAT.PATService.UploadLOBRequest request) {
            return base.Channel.GetLOBWarningsAndErrors(request);
        }
        
        public PAT.PATService.LOBUpload GetLOBWarningsAndErrors(string ip_address, LOBDetailRecord[] lobDetailRecords, PAT.PATService.LOBMasterRecord lobMaster, string system_id, out string response, out LOBValidResponse[] validationResponses) {
            PAT.PATService.UploadLOBRequest inValue = new PAT.PATService.UploadLOBRequest();
            inValue.ip_address = ip_address;
            inValue.lobDetailRecords = lobDetailRecords;
            inValue.lobMaster = lobMaster;
            inValue.system_id = system_id;
            PAT.PATService.UploadLOBResponse retVal = ((PAT.PATService.PatLOBPortType)(this)).GetLOBWarningsAndErrors(inValue);
            response = retVal.response;
            validationResponses = retVal.validationResponses;
            return retVal.origUpload;
        }
    }
}
